name: Tests
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - run: ./gralew clean test
      #- uses: Xotabu4/selenoid-github-action@v2

